# Generated by Django 3.0.14 on 2023-01-14 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num_table', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер стола')),
                ('seats', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('shape', models.CharField(choices=[('rectangular', 'Прямоугольный'), ('oval', 'Овальный')], max_length=50, verbose_name='Форма стала')),
                ('x', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Положене стола по x(от 1 до 100)')),
                ('y', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Положение стола по y(от 1 до 100)')),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Ширина стола(от 1 до 100)')),
                ('length', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Длина стола(от 1 до 100)')),
            ],
        ),
    ]
