# Generated by Django 3.0.14 on 2023-01-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
